import Link from "next/link";
import { ArrowRight, Download } from "lucide-react";
import { PageShell } from "./components";
import { experiences, projects } from "./content";
export default function Home(){return <PageShell>
 <section className="hero clean-shell"><p className="overline">Atlanta, Georgia · Open to 2027 opportunities</p><h1>Software engineer<br/>with a <em>data-informed</em><br/>way of thinking.</h1><p className="intro">I’m Cherisha, an MS Computer Science student at Georgia State University. I build reliable software and turn complex data into clear, useful experiences.</p><div className="actions"><Link className="button dark" href="/projects">View selected work <ArrowRight/></Link><a className="button light" href="/Cherisha_KG_ATS_Resume.pdf" target="_blank">View résumé <Download/></a></div></section>
 <section className="focus clean-shell"><div><span>01</span><h2>Software Engineering</h2><p>Full-stack and mobile products built around usable flows, maintainable systems, and real user needs.</p></div><div><span>02</span><h2>Data Analysis</h2><p>Data preparation, modeling, dashboards, and visual explanations that support better decisions.</p></div></section>
 <section className="home-work clean-shell"><div className="section-title"><div><p>Selected work</p><h2>A few things I’ve built.</h2></div><Link href="/projects">All projects <ArrowRight/></Link></div><div className="featured-grid">{projects.slice(0,3).map((p,i)=><Link className="project-card" href={`/projects/${p.slug}`} key={p.slug}><span>{String(i+1).padStart(2,"0")} · {p.type}</span><h3>{p.title}</h3><p>{p.summary}</p><div>{p.stack.slice(0,3).map(s=><b key={s}>{s}</b>)}</div><small>View project <ArrowRight/></small></Link>)}</div></section>
 <section className="home-experience clean-shell"><div className="section-title"><div><p>Experience</p><h2>Learning by building.</h2></div><Link href="/experience">Full experience <ArrowRight/></Link></div>{experiences.slice(0,3).map(e=><Link className="experience-row" href={`/experience/${e.slug}`} key={e.slug}><time>{e.year}</time><div><h3>{e.role}</h3><p>{e.company}</p></div><span>{e.summary}</span><ArrowRight/></Link>)}</section>
 <section className="closing clean-shell"><p>Have a role or project in mind?</p><h2>Let’s build something useful.</h2><a href="https://www.linkedin.com/messaging/" target="_blank">Start a conversation <ArrowRight/></a></section>
</PageShell>}
